name: Deploying multiple Lambdas

on:
  push:
    branches:
      - main

jobs:
  lambda1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt -t ./package; fi
      - name: Package Lambda function
        run: |
          cp ./lambda_function.py ./package/
          cd package
          zip -r ../lambda1.zip .
      - name: Deploy Lambda function
        run: aws lambda update-function-code --function-name=paramikoConnect --zip-file=fileb://lambda1.zip